module.exports = `## {{ title }}
{{#if body}}
{{ body }}
---
{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ fileName }}#{{ range }}
---
{{/if}}
###### This comment was generated by [todo]({{ todoUrl }}) based on a \`{{ keyword }}\` comment in {{ sha }} in #{{ number }}.{{ username }}`;
