module.exports = `## {{ title }}
{{#if body}}
{{ body }}

---
{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ fileName }}#{{ range }}
---
{{/if}}
###### :rocket: This comment was generated by the [automations bot]({{ todoUrl }}) based on a \`{{ keyword }}\` comment in {{ sha }} in #{{ number }}. cc @{{ username }}`;
