module.exports = `{{#if body}}
{{ body }}
---
{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ fileName }}#{{ range }}
---
{{/if}}
###### This issue was generated by [todo]({{ todoUrl }}) based on a \`{{ keyword }}\` comment in {{ sha }} when #{{ number }} was merged.{{ username }}`;
