on:
  pull_request:
    types: [opened,synchronize,closed]
  push:
  issues:
    types: [edited]
name: Project management automations

jobs:
  project-management-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          ref: trunk
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
